EXTRN ARITH:NEAR
.MODEL SMALL
.STACK 100h
.DATA
    MSG1 DB 'ENTER FIRST NUMBER - 2 DIGITS: $'
    MSG2 DB 0Dh, 0Ah,'ENTER SECOND NUMBER - 1 DIGIT: $'
    MSG3 DB 0Dh, 0Ah,'PRESS KEY TO SELECT THE OPERATION TO BE PERFORMED:'
    MSG4 DB 0Dh, 0Ah,'1:ADDITION',09h,09h,'2:SUBTRACTION$'
.CODE
MAIN PROC
	MOV AX,@DATA
	MOV DS,AX
	LEA DX,MSG1
	MOV AH,9
	INT 21h
	MOV AH,1
	INT 21h
	MOV BH,AL
	INT 21h
	MOV BL,AL
	LEA DX,MSG2
	MOV AH,9
	INT 21h
	MOV AH,1
	INT 21h
	MOV CL,AL
	LEA DX,MSG3
	MOV AH,9
	INT 21h
	MOV AH,8
	INT 21h
	CALL ARITH
	MOV AH,4Ch
	INT 21h
    MAIN ENDP
END MAIN